#!/bin/sh

# This script downloads, builds, and installs the Debian dpkg and fakeroot
# packages, which are needed to build Debian binary packages.  Use the variable
# definitions below to configure the build process.

START_DIR=/root
WORKING_DIR=$START_DIR/debian-build-tools-tmp
INSTALL_DIR=/root/debian-build-tools
LOG_DIR=$WORKING_DIR/logs


#Note that versions after this are incompatible with SL7/RHEL7/CentOS7 currently
DPKG_VERSION=1.18.1 
DPKG_SOURCE_TARBALL=dpkg_${DPKG_VERSION}.tar.xz
DPKG_SOURCE_DIR=$WORKING_DIR/dpkg-${DPKG_VERSION}

#FAKEROOT_VERSION=1.11
#FAKEROOT_SOURCE_TARBALL=fakeroot_${FAKEROOT_VERSION}.tar.xz
#FAKEROOT_SOURCE_DIR=$WORKING_DIR/fakeroot-${FAKEROOT_VERSION}

DEBSIGS_VERSION=0.1.18
DEBSIGS_SOURCE_TARBALL=debsigs_${DEBSIGS_VERSION}.tar.xz
DEBSIGS_SOURCE_DIR=$WORKING_DIR/debsigs-${DEBSIGS_VERSION}

# Error-handling functions
handle_download_error()
{
    if [ $? -ne 0 ]
    then
        echo 'FAILED!'
        echo 'Check network connections and disk write access and try again.'
        exit 1
    fi
}
handle_logged_error()
{
    if [ $? -ne 0 ]
    then
        echo 'FAILED!'
        echo "Check '$1' for errors."
        echo 'When errors are fixed, rerun this script.'
        exit 1
    fi
}

# Setup
if [ ! -d $WORKING_DIR ]
then
    mkdir $WORKING_DIR
fi
if [ ! -d $LOG_DIR ]
then
    mkdir $LOG_DIR
fi
if [ ! -d $INSTALL_DIR ]
then
    mkdir $INSTALL_DIR
fi
cd $WORKING_DIR

# FETCH SOURCES
echo 'fetching dpkg source'
    #curl -sSLO http://ftp.de.debian.org/debian/pool/main/d/dpkg/$DPKG_SOURCE_TARBALL
    curl -sSLO https://snapshot.debian.org/archive/debian/20150530T041415Z/pool/main/d/dpkg/dpkg_1.18.1.tar.xz
#git clone https://salsa.debian.org/dpkg-team/dpkg.git $START_DIR/dpkg
handle_download_error

#if [ ! -f $FAKEROOT_SOURCE_TARBALL ]
#then
#    echo 'fetching fakeroot source'
#    curl -sSLO http://ftp.de.debian.org/debian/pool/main/f/fakeroot/$FAKEROOT_SOURCE_TARBALL
#    handle_download_error
#fi
if [ ! -f $DEBSIGS_SOURCE_TARBALL ]
then
    echo 'fetching debsigs source'
    curl -sSLO http://ftp.de.debian.org/debian/pool/main/d/debsigs/$DEBSIGS_SOURCE_TARBALL
    handle_download_error
fi

# UNPACK SOURCES
if [ ! -d $DPKG_SOURCE_DIR ]
then
   echo 'unpacking dpkg source'
    tar --xz -xf $DPKG_SOURCE_TARBALL
fi
#if [ ! -d $FAKEROOT_SOURCE_DIR ]
#then
#    echo 'unpacking fakeroot source'
#    tar xzf $FAKEROOT_SOURCE_TARBALL
#fi
if [ ! -d $DEBSIGS_SOURCE_DIR ]
then
    echo 'unpacking debisgs source'
    tar --xz -xf $DEBSIGS_SOURCE_TARBALL
fi

# BUILD DPKG
cd $DPKG_SOURCE_DIR
if [ ! -f Makefile ]
then
    DPKG_CONFIG_OPTIONS="--prefix=$INSTALL_DIR --without-selinux"
    echo "configuring dpkg with '$DPKG_CONFIG_OPTIONS'"
    #./autogen
    ./configure $DPKG_CONFIG_OPTIONS > $LOG_DIR/dpkg-configure.log 2>&1
    #cat $LOG_DIR/dpkg-configure.log
    handle_logged_error $LOG_DIR/dpkg-configure.log
fi
if [ ! -f src/dpkg ]
then
    echo 'building dpkg'
    make >$LOG_DIR/dpkg-build.log 2>&1
    handle_logged_error $LOG_DIR/dpkg-build.log
fi
if [ ! -f $INSTALL_DIR/bin/dpkg ]
then
    echo 'installing dpkg'
    make install >$LOG_DIR/dpkg-install.log 2>&1
    handle_logged_error $LOG_DIR/dpkg-install.log
fi

# BUILD FAKEROOT
#cd $FAKEROOT_SOURCE_DIR
#if [ ! -f Makefile ]
#then
#    FAKEROOT_CONFIG_OPTIONS="--prefix=$INSTALL_DIR"
#    echo "configuring fakeroot with '$FAKEROOT_CONFIG_OPTIONS'"
#    ./configure $FAKEROOT_CONFIG_OPTIONS >$LOG_DIR/fakeroot-configure.log 2>&1
#    handle_logged_error $LOG_DIR/fakeroot-configure.log
#fi
#if [ ! -f faked ]
#then
#    echo 'building fakeroot'
#    make >$LOG_DIR/fakeroot-build.log 2>&1
#    handle_logged_error $LOG_DIR/fakeroot-build.log
#fi
#$if [ ! -f $INSTALL_DIR/bin/fakeroot ]
#t#hen
#    echo 'installing fakeroot'
#    make install >$LOG_DIR/fakeroot-install.log 2>&1
#    handle_logged_error $LOG_DIR/fakeroot-install.log
#fi

# COPY NECESSARY DEBSIGS FILES
cd $DEBSIGS_SOURCE_DIR
if [ ! -e $INSTALL_DIR/perl5lib/Debian/debsigs ]
then
    echo "copying necessary perl modules"
    mkdir -p $INSTALL_DIR/perl5lib/Debian/debsigs 
    cp *.pm $INSTALL_DIR/perl5lib/Debian/debsigs/ 2>&1
    handle_logged_error $LOG_DIR/debsigs-perl-install.log

fi
if [ ! -f $INSTALL_DIR/bin/debsigs ]
then
    echo 'installing debsigs'
    #mkdir $INSTALL_DIR/bin 
    cp debsigs $INSTALL_DIR/bin/debsigs
    handle_logged_error $LOG_DIR/debsigs-install.log
    chmod +x $INSTALL_DIR/bin/debsigs
fi

# Creating setup.sh 
if [ ! -f $INSTALL_DIR/setup.sh ]
then
    echo "Creating $INSTALL_DIR/setup.sh"
    echo "export PATH=\$PATH:$INSTALL_DIR/bin/" > $INSTALL_DIR/setup.sh
    echo "export PERL5LIB=\$PERL5LIB:$INSTALL_DIR/perl5lib/" >>  $INSTALL_DIR/setup.sh
    chmod +x $INSTALL_DIR/setup.sh
fi
